- name: Create keyrings-temp directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/apt/keyrings-temp/
    state: directory
    mode: "0755"

# VS Code keyrings and sources list

- name: Retrieve gpg key for VS Code
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings-temp/microsoft.asc
    mode: a+r

- name: Covert .asc key for VS Code # noqa: command-instead-of-shell no-changed-when
  ansible.builtin.shell:
    cmd: gpg -o /etc/apt/keyrings/packages.microsoft.gpg --dearmor /etc/apt/keyrings-temp/microsoft.asc

- name: Add apt repository for VS Code
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main

- name: Remove stagnant gpg key for VS Code
  ansible.builtin.file:
    path: /etc/apt/keyrings-temp/microsoft.asc
    state: absent
