- name: Install necessary packages
  ansible.builtin.apt:
    pkg:
      - make
      - gawk

- name: Clone the Ble.sh repository # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/akinomyoga/ble.sh.git
    dest: /home/{{ user }}/ble.sh
    depth: 1

- name: Build 'install' target with extra arguments
  community.general.make:
    chdir: /home/{{ user }}/ble.sh
    target: install
    params:
      PREFIX: /home/{{ user }}/.local

- name: Source the Ble.sh shell script # noqa: no-changed-when
  ansible.builtin.shell:
    cmd: echo 'source /home/{{ user }}/.local/share/blesh/ble.sh' >> /home/{{ user }}/.bashrc
