- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: '{{ user }}'
    mode: '0755'

- name: Generate ssh keypair
  community.crypto.openssh_keypair:
    path: /home/{{ user }}/.ssh/id_ed25519
    type: ed25519
