---
- name: Configure git globally
  hosts: localhost
  connection: local
  vars_files:
    - ../vars.yaml

  tasks:

    - name: Run ssh tasks
      ansible.builtin.include_tasks: tasks/ssh.yaml
      tags: ssh

    - name: Run git tasks
      ansible.builtin.include_tasks: tasks/git.yaml
      tags: git
