---
- name: Configure git globally
  hosts: localhost
  connection: local
  vars_prompt:

    - name: user
      prompt: enter your username for the system you are setting up.
      private: false

    - name: email
      prompt: what email are you using for git shit?

  tasks:

    - name: Run ssh tasks
      ansible.builtin.include_tasks: tasks/ssh.yaml
      tags: ssh

    - name: Run git tasks
      ansible.builtin.include_tasks: tasks/git.yaml
      tags: git
