---
- name: Docker setup and install
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../vars.yaml

  tasks:

    - name: Prepare system for Docker services
      ansible.builtin.include_tasks: tasks/docker_prep.yaml

    - name: Setup up Docker keyrings and source list
      ansible.builtin.include_tasks: tasks/apt_keys_docker.yaml

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - uidmap # for rootless Docker
        clean: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: '{{ user }}'
        groups:
          - docker
        append: true

    - name: Print reminder to set logging driver
      ansible.builtin.debug:
        msg: >
          Docker install is complete. Once provisioning is completed, remem
          ber to set the logging driver in /etc/docker/daemon.json

    - name: Clear cache
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
