---
- name: Docker setup and install
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../vars.yaml

  tasks:

    - name: Prepare system for Docker services
      ansible.builtin.include_tasks: tasks/docker_prep.yaml

    - name: Setup up Docker keyrings and source list
      ansible.builtin.include_tasks: tasks/apt_keys_docker.yaml

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - uidmap # for rootless Docker
        clean: true

    - name: Clear cache
      ansible.builtin.apt:
        autoclean: true
        autoremove: true

    - name: Run Post-Install tasks
      ansible.builtin.include_tasks: tasks/docker_post_install.yaml

    - name: Print reminder to set logging driver
      ansible.builtin.pause:
        prompt: |
          Docker install is complete. Once provisioning is completed, remember to set the logging driver in /etc/docker/daemon.json
          Default is json-file. For more information, see https://docs.docker.com/engine/logging/drivers/json-file/
