---
- name: Install Warp Terminal
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Retrieve Warp Terminal package
      ansible.builtin.get_url:
        url: https://app.warp.dev/download?package=deb_arm64
        dest: /tmp/warp.deb
        mode: a+r

    - name: Install Warp
      ansible.builtin.apt:
        deb: /tmp/warp.deb

    - name: Remove .deb file
      ansible.builtin.file:
        path: /tmp/warp.deb
        state: absent
