---
- name: Setup ssh and git config
  hosts: localhost
  connection: local

- name: Set git config
  ansible.builtin.import_playbook: git_config.yaml

- name: Provision Debian VM
  hosts: localhost
  connection: local
  become: true

- name: Install Docker
  ansible.builtin.import_playbook: ./install_docker.yaml

- name: Install GitHub CLI
  ansible.builtin.import_playbook: ./install_gh.yaml

- name: Install Warp Terminal
  ansible.builtin.import_playbook: ./install_warp.yaml

- name: Install VS Code
  ansible.builtin.import_playbook: ./install_code.yaml
