---
- name: Setup ssh and git config
  hosts: localhost
  connection: local

  tasks:

    - name: Create ssh keypair
      ansible.builtin.include_tasks: tasks/ssh.yaml

- name: Set git config
  ansible.builtin.import_playbook: git_config.yaml

- name: Docker Prep
  hosts: localhost
  connection: local
  become: true

- name: Gut existing Docker installations
  ansible.builtin.import_playbook: docker_prep.yaml

- name: Provision Debian VM
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Update keyrings and sources lists
      ansible.builtin.include_tasks:
        file: tasks/apt_keys.yaml

    - name: Install all the packages
      ansible.builtin.include_tasks: tasks/apt_install.yaml

    - name: Install Oh My Bash
      ansible.builtin.include_tasks: tasks/ohmybash.yaml

    - name: Install Ble.sh
      ansible.builtin.include_tasks: tasks/ble.sh.yaml
