---
- name: Remove default packages
  hosts: localhost
  connection: local
  become: true

  tasks:

    # Most k* apps are installed with KDE Plasma

    - name: Remove apt packages
      ansible.builtin.apt:
        pkg:
          - libreoffice-*
          - konqueror
          - kate
          - kmail*
          - gimp
        state: absent

    - name: Remove dependencies and clear cache
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
