---
- name: Remove default packages
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Remove apt packages
      ansible.builtin.apt:
        pkg:
          - libreoffice-*
        state: absent

    - name: Remove dependencies and clear cache
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
