---
- name: Warp Terminal
  hosts: localhost
  connection: local
  become: true

  tasks:

    # Warp Terminal keyrings and sources list

    - name: Retrieve gpg key for Warp # noqa: command-instead-of-module no-changed-when
      ansible.builtin.get_url:
        url: https://releases.warp.dev/linux/keys/warp.asc
        dest: /etc/apt/keyrings/warpdotdev.asc
        mode: a+r

    - name: Convert asc key for Warp # noqa: no-changed-when
      ansible.builtin.command:
        cmd: gpg --dearmor /etc/apt/keyrings/warpdotdev.asc

    - name: Add apt repository for Warp
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main
