name: ansible-lint
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@e918e02374cc9148abfe6d0fa04417ee89f0def9
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
